### ISSUE TITLE
Replace PreparedStatement with simple update

### ISSUE THREAD

**Issue by serban-petrescu** [stoiandan/OnlineShop#1]
https://github.com/stoiandan/OnlineShop/blob/9401887ed602eaf469c1ff349c2d0b4c32a6be53/src/main/java/ro/msg/learning/shop/repositories/ProductRespository.java#L39

See https://docs.spring.io/spring/docs/current/javadoc-api/org/springframework/jdbc/core/JdbcTemplate.html#update-java.lang.String-java.lang.Object...-

**Comment by stoiandan** [comment]
Some queries could be replace (delete for instance), but insert is hard to replace since objects cannot be appended to a string like primitive types and strings are.

**Comment by serban-petrescu** [comment]
Not yet really what I wanted :) Building SQLs by concatenating values into some string is never a good idea. What I meant is that you should use the update method linked above like this:

```java
	public void remove(int id) {
		jdbcTemplate.update("DELETE * FROM PRODUCT WHERE id = ?", id);
	}
```

instead of using the connection directly. You should only use the jdbc connection when you are doing more advanced stuff (not simply creating a prepared statement and running it).

**Comment by stoiandan** [comment]
Done!
